#!/bin/bash
echo starts

srun --nodes=1 --ntasks=1 --gpus=8 --exclusive --container-mounts=/lustre/fsw/portfolios/dir/users/haotiany/joint_training/:/joint_training --container-image=./docker_images/imaginaire4_v9.2.2.sqsh /bin/bash /joint_training/jtrain_from_titok/exp_scripts/main_newloss.sh titok_b512_4096_12.yaml 32 2e-4 True True 0.5 False 0.5 results_final titok_b512_4096_12.yaml+method=ours+p_mean=0.5+anneal=False+finetune=False px try_paper_runs  > logs/titok_b512_4096_12.yaml+method=ours+p_mean=0.5+anneal=False+finetune=False.log 2>&1 &

srun --nodes=1 --ntasks=1 --gpus=8 --exclusive --container-mounts=/lustre/fsw/portfolios/dir/users/haotiany/joint_training/:/joint_training --container-image=./docker_images/imaginaire4_v9.2.2.sqsh /bin/bash /joint_training/jtrain_from_titok/exp_scripts/main_newloss.sh titok_b512_4096_12.yaml 32 2e-4 True True 0.5 False 0.5 results_final titok_b512_4096_12.yaml+method=ours+p_mean=0.5+anneal=False+finetune=True px try_paper_runs results_try_new_design/titok_b512_4096_12+elbo_mode=+nll_only=0.5+rate_weight=1+elbo_lower=0.5+elbo_upper=0.5/checkpoint-250000/unwrapped_model/pytorch_model.bin > logs/titok_b512_4096_12.yaml+method=ours+p_mean=0.5+anneal=False+finetune=True.log 2>&1 &

srun --nodes=1 --ntasks=1 --gpus=8 --exclusive --container-mounts=/lustre/fsw/portfolios/dir/users/haotiany/joint_training/:/joint_training --container-image=./docker_images/imaginaire4_v9.2.2.sqsh /bin/bash /joint_training/jtrain_from_titok/exp_scripts/main_newloss.sh titok_b512_4096_12.yaml 32 2e-4 True True 0.5 True 0.5 results_final titok_b512_4096_12.yaml+method=ours+p_mean=0.5+anneal=True+finetune=False anneal_to_px try_paper_runs  > logs/titok_b512_4096_12.yaml+method=ours+p_mean=0.5+anneal=True+finetune=False.log 2>&1 &

srun --nodes=1 --ntasks=1 --gpus=8 --exclusive --container-mounts=/lustre/fsw/portfolios/dir/users/haotiany/joint_training/:/joint_training --container-image=./docker_images/imaginaire4_v9.2.2.sqsh /bin/bash /joint_training/jtrain_from_titok/exp_scripts/main_newloss.sh titok_b512_4096_12.yaml 32 2e-4 True True 0.5 True 0.5 results_final titok_b512_4096_12.yaml+method=ours+p_mean=0.5+anneal=True+finetune=True anneal_to_px try_paper_runs results_try_new_design/titok_b512_4096_12+elbo_mode=+nll_only=0.5+rate_weight=1+elbo_lower=0.5+elbo_upper=0.5/checkpoint-250000/unwrapped_model/pytorch_model.bin > logs/titok_b512_4096_12.yaml+method=ours+p_mean=0.5+anneal=True+finetune=True.log 2>&1 &
wait
echo finished
